wandb_version: 1

learning_rate:
  desc: null
  value: 0.01
architecture:
  desc: null
  value: Deep Ensemble
dataset:
  desc: null
  value: regression
epochs:
  desc: null
  value: 100
batch_size:
  desc: null
  value: 40
hidden_dim:
  desc: null
  value: 40
n_hidden:
  desc: null
  value: 4
_wandb:
  desc: null
  value:
    python_version: 3.11.7
    cli_version: 0.17.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1716232313
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 16
      - 23
      - 61
      4: 3.11.7
      5: 0.17.0
      8:
      - 5
      - 13
      13: linux-x86_64
