wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.7
    cli_version: 0.17.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1716855079
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 13
      - 23
      - 37
      4: 3.11.7
      5: 0.17.0
      8:
      - 5
      - 13
      13: linux-x86_64
epochs:
  desc: null
  value: 50
lr:
  desc: null
  value: 0.01
